Updated with changes from OmniGroup svn [317267:318327]

diff --git a/Scripts/BuildStringsFromTarget b/Scripts/BuildStringsFromTarget
--- a/Scripts/BuildStringsFromTarget
+++ b/Scripts/BuildStringsFromTarget
@@ -27,71 +27,88 @@ DEVELOPMENT_REGION="en"
 # Build the strings file(s) into a separate directory so we can avoid mucking with timestamps in the build output unless needed (see below). Don’t move the file list into place unless building it succeeds.
 STRINGS_DIR="$DERIVED_FILES_DIR/BuildStringsFromTarget-$TARGET_NAME"
 TMP_OUTPUT="$STRINGS_DIR/$DEVELOPMENT_REGION".lproj
-LOCALIZABLE_FILE_LIST="$TMP_OUTPUT"/files
-
-if [ -d "$STRINGS_DIR" ]; then
-    if [ -f "$LOCALIZABLE_FILE_LIST" ]; then
-        # If we've run before and nothing has changed, bail
-        NEWER="no"
-        
-        echo "$LOCALIZABLE_FILE_LIST has mtime `stat -f m $LOCALIZABLE_FILE_LIST`"
-        cat "$LOCALIZABLE_FILE_LIST" | while read file; do
-            if [ "$file" -nt "$LOCALIZABLE_FILE_LIST" ]; then
-              NEWER="yes"
-            fi
-        done
-        
-        if [ "$NEWER" = "no" ]; then
-            echo "No new localizable files since `stat -f %Sm $LOCALIZABLE_FILE_LIST`; exiting"
-            exit 0
-        fi
-    fi
-    
-    # Otherwise start from scratch and continue on
-    rm -rf "$STRINGS_DIR"
-fi
+LOCALIZABLE_FILE_LIST="$TMP_OUTPUT"/localizable-files
 
 mkdir -p "$STRINGS_DIR"
-mkdir "$TMP_OUTPUT"
+mkdir -p "$TMP_OUTPUT"
 
-# Gather the source files and the project file that defined them into a list, which we'll use for early-out
-echo "$PROJECT_FILE_PATH"/project.pbxproj  > "$LOCALIZABLE_FILE_LIST"-tmp
+# Gather the project file and source files from the target in symbolic form.
+echo "\$(SRCROOT)/"$("$SCRIPTS_DIR"/RelativePath "$PROJECT_FILE_PATH" "$SRCROOT")/project.pbxproj  > "$LOCALIZABLE_FILE_LIST"
+$SCRIPTS_DIR/ListSourceFilesInTarget --keep-variables "$TARGET_NAME" c,m,swift,xib,storyboard "$PROJECT_FILE_PATH" >> "$LOCALIZABLE_FILE_LIST" 
+
+# For Xcode 10's build system, we should have exactly one input file specified that is the list of source files in the target that have localizable strings.
+# Make sure that the list of input files we made matches what we were given (and if not, echo a command that can be copied to update the input file).
+SYMBOLIC_LOCALIZABLE_FILE_LIST="$SRCROOT/$TARGET_NAME.xcfilelist"
+
+if [ "${SCRIPT_INPUT_FILE_LIST_COUNT:-0}" != "1" ] || ! cmp --quiet "$LOCALIZABLE_FILE_LIST" "$SYMBOLIC_LOCALIZABLE_FILE_LIST"; then
+    
+    if [ "$OMNI_BUILD_STRINGS_INPUT_MISSING" = "warn" ]; then
+        echo "** No inputs declared for BuildStringsFromTarget; running older verion **"
+        exec "$SCRIPTS_DIR/BuildStringsFromTarget-Old" $*
+    fi
+    
+    # Xcode copies the xcfilelist input to a temporary spot and rewrites it with all absolute paths (and variables replaced).
+    # We expect a particular naming scheme for these files to make the build phases easy to set up.
+    if [ "$SCRIPT_INPUT_FILE_LIST_COUNT" = "1" ]; then
+        echo "*** Error: Out of date localizable input file list:"
+        diff "$SYMBOLIC_LOCALIZABLE_FILE_LIST" "$LOCALIZABLE_FILE_LIST" || true
+    else
+        echo "*** Error: Missing localizable input file list:"
+    fi
+    
+    echo
+    echo "cp \"$LOCALIZABLE_FILE_LIST\" \"$SYMBOLIC_LOCALIZABLE_FILE_LIST\""
+    echo 
+    echo "Must also update the Build String Files shell script phase to include an input files item of:"
+    echo
+    echo "  \$(SRCROOT)/\$(TARGET_NAME).xcfilelist"
+    echo
+    echo "and an output (single) file item of:"
+    echo
+    echo "  \$(DERIVED_FILE_DIR)/\$(TARGET_NAME)-BuildStringFiles"
+    echo
+    exit 1
+fi
+
+# Now that we know our symbolic list of input files matches, read the preprocessed version that Xcode built
 source_files=()
-$SCRIPTS_DIR/ListSourceFilesInTarget "$TARGET_NAME" c,m,swift "$PROJECT_FILE_PATH" | while read f; do
-   source_files+=($f)
-   echo "$f" >> "$LOCALIZABLE_FILE_LIST"-tmp
+cat "$SCRIPT_INPUT_FILE_LIST_0" | while read f; do
+    case "$f:x" in
+    xib,storyboard)
+        # Build English strings for every xib using base localizations
+        xib_basename=`basename $x`
+        if [[ "$x" =~ "Base.lproj/$xib_basename\$" ]]; then
+            string_table_name="${xib_basename%.*}"
+            echo "Creating string table '$string_table_name' from $x" # without this line here, zsh segfaults. (!?)
+		
+    		# Extract the strings
+            ibtool --output-format human-readable-text --export-strings-file "$TMP_OUTPUT/${string_table_name}.strings" "$SRCROOT/$x"
+		
+    		# ibtool writes UTF-16 and doesn't seem to have a switch to requested a string encoding. Also, when it emits 'empty' strings files, they have a single newline.
+    		echo "  -- converting to utf-8"
+    		$SCRIPTS_DIR/ChangeStringEncoding --input utf-16 --output utf-8 "$TMP_OUTPUT/${string_table_name}.strings"
+		
+    		# But only copy the strings file into the product if it is non-empty
+    		size=$(stat -n -f %z "$TMP_OUTPUT/${string_table_name}.strings")
+    		if [ $size -gt 1 ]; then
+    	        EXPECTED_STRINGS_FILES+=$string_table_name
+    		else
+    			rm "$TMP_OUTPUT/${string_table_name}.strings"
+    			echo "  -- ignoring since it is empty"
+    		fi
+        fi
+        ;;
+    *)
+        source_files+=($f)
+        ;;
+    esac
 done
 
+# Generate strings from the other source files
 if [ $#source_files -gt 0 ]; then
     # genstrings doesn't handle Swift files. Radar 22761905.
 	xcrun extractLocStrings -u -q -o "$TMP_OUTPUT" $source_files
 fi
-
-# Build English strings for every xib using base localizations
-$SCRIPTS_DIR/ListSourceFilesInTarget "$TARGET_NAME" xib,storyboard "$PROJECT_FILE_PATH" | while read x; do
-    xib_basename=`basename $x`
-    if [[ "$x" =~ "Base.lproj/$xib_basename\$" ]]; then
-        string_table_name="${xib_basename%.*}"
-        echo "$x" >> "$LOCALIZABLE_FILE_LIST"-tmp
-        echo "Creating string table '$string_table_name' from $x" # without this line here, zsh segfaults. (!?)
-		
-		# Extract the strings
-        ibtool --output-format human-readable-text --export-strings-file "$TMP_OUTPUT/${string_table_name}.strings" "$SRCROOT/$x"
-		
-		# ibtool writes UTF-16 and doesn't seem to have a switch to requested a string encoding. Also, when it emits 'empty' strings files, they have a single newline.
-		echo "  -- converting to utf-8"
-		$SCRIPTS_DIR/ChangeStringEncoding --input utf-16 --output utf-8 "$TMP_OUTPUT/${string_table_name}.strings"
-		
-		# But only copy the strings file into the product if it is non-empty
-		size=$(stat -n -f %z "$TMP_OUTPUT/${string_table_name}.strings")
-		if [ $size -gt 1 ]; then
-	        EXPECTED_STRINGS_FILES+=$string_table_name
-		else
-			rm "$TMP_OUTPUT/${string_table_name}.strings"
-			echo "  -- ignoring since it is empty"
-		fi
-    fi
-done
 
 FIX_STRINGS_FILE="$BUILD_DIR/$CONFIGURATION"/FixStringsFile
 
@@ -145,10 +162,11 @@ while [ $#EXPECTED_STRINGS_FILES != 0 ]; do
     rm "$table_file"
 done
 
+
 unexpected="no"
 for x in "$TMP_OUTPUT"/*(N); do
-    echo "Checking $x against ${LOCALIZABLE_FILE_LIST}-tmp"
-    if [ "$x" != "$LOCALIZABLE_FILE_LIST"-tmp ]; then
+    echo "Checking $x against ${LOCALIZABLE_FILE_LIST}"
+    if [ "$x" != "$LOCALIZABLE_FILE_LIST" ]; then
         echo >&2 "Unexpected string file emitted: $x"
         unexpected="yes"
     fi
@@ -156,9 +174,7 @@ done
 
 if [ $unexpected = "yes" ]; then
     exit 1
-else
-    mv "$LOCALIZABLE_FILE_LIST"-tmp "$LOCALIZABLE_FILE_LIST"
-
-    echo "Localized files:"
-    cat "$LOCALIZABLE_FILE_LIST"
 fi
+
+# We should have exactly one output, which is a dummy marker file for us to touch on success.
+touch "$SCRIPT_OUTPUT_FILE_0"
